filterFunctions:
  [
    "Test.fromInt(int256)",
    "Test.add(int128,int128)",
    "Test.sub(int128,int128)",
    "Test.mul(int128,int128)",
    "Test.div(int128,int128)",
    "Test.fromInt(int256)",
    "Test.fromInt(int256)",
    "Test.pow(int128,uint256)",
    "Test.neg(int128)",
    "Test.inv(int128)",
    "Test.sqrt(int128)",
    "Test.abs(int128)",
    "Test.log_2(int128)",
    "ln(int128)",
    "exp_2(int128)",
    "exp(int128)",
    "muli(int128,int256)",
    "divi(int256,int256)",
    "divu(uint256,uint256)",
    "gavg(int128,int128)",
    "fromInt(int256)",
    "toInt(int128)",
    "fromUInt(uint256)",
  ]
testMode: assertion
seqLen: 1
testLimit: 10000
corpusDir: "corpus"
